Repository JoaoDanielRufino/go-input-autocomplete, pull requests merged in 2020-10, with the labels that each got.

#9 [BUG FIX] Fixed bug on absolute path
  .gitignore
  autocomplete.go
  cmd.go
  cmd/main.go
  input_autocomplete.go
Labels: Hacktoberfest

#12 Make next-segment-discovery case insensitive
  autocomplete.go
Labels: hacktoberfest, hacktoberfest-accepted

#13 changed linux and darwin to unix
  autocomplete.go
  cmd.go
Labels: hacktoberfest, hacktoberfest-accepted

#17 Fixing Hidden files/directories support
  cmd.go
Labels: hacktoberfest

#19 Fixing Path: panic: runtime error: while pressing tab as input #18
  input.go
Labels: bug, hacktoberfest, hacktoberfest-accepted

#22 Add tests to input.go
  input_test.go
Labels: hacktoberfest

#27 fix format of the .go files using gofmt
  autocomplete.go
  autocomplete_test.go
  input.go
  input_test.go
Labels: hacktoberfest, hacktoberfest-accepted

#26 add makefile support to build and test the package
  Makefile
Labels: hacktoberfest, hacktoberfest-accepted

#29 add abs path test case
  autocomplete_test.go
Labels: hacktoberfest, hacktoberfest-accepted

#30 add test for char insertion in middle of word
  input_test.go
Labels: hacktoberfest, hacktoberfest-accepted
